### ISSUE TITLE
Next patches

### ISSUE THREAD

**Issue by stbestichhh** [stbestichhh/stlib-testing#20]
### Patch 0.0.6
- [ ] Add more methods 
- [ ] Add mocking functionality
- [ ] Add watch mode???

### Patch 0.0.7
- [ ] Add watch mode
